Fix LCD output and add translations
gudnimg/Prusa-Firmware pull request #8
Opened 2024-08-26 08:08 UTC by 3d-gussner

2024-08-26 08:48 UTC, 3d-gussner commented
Please verify and approve the new translations. Remember that the message is limited to 20 characters and 3 rows,
- [x] :czech_republic:  @DRracer
- [X] :de: @3d-gussner
- [x] :es: 
- [x] :fr: @Ilovemyhous @ErwanAliasr1
- [x] :it: @wavexx
- [x] :poland: @arekm
- [x] :netherlands: @vintagepc @stelgenhof
- [x] :romania: @leptun @Hauzman
- [x] :hungary: @AttilaSVK @Hauzman
- [ ] :croatia: @Prime1910 @PRPA041
- [x] :slovakia: @ingbrzy @shatter136
- [ ] :sweden: @Painkiller56
- [ ] :norway: @OS-kar @trondkla

2024-08-26 08:50 UTC, ErwanAliasr1 approved these changes
FR is :ok:

2024-08-26 08:53 UTC, arekm approved these changes
PL is OK.

2024-08-26 09:34 UTC, Ro3Deee commented
@leptun, for Romanian:
Instead "Nu există filament încărcat" I'd use "Filamentul nu este încărcat" sau "Filamentul nu este detectat"

2024-08-26 09:50 UTC, 3d-gussner commented
> @leptun, for Romanian: Instead "Nu există filament încărcat" I'd use "Filamentul nu este încărcat" sau "Filamentul nu este detectat"

Thanks @petrubecheru @Hauzman. Which is the preferred one?
1. Filamentul nu este încărcat :tada: 
2. Filamentul nu este detectat :heart:

2024-08-26 12:04 UTC, stelgenhof requested changes

2024-08-26 12:04 UTC, stelgenhof commented on lang/po/Firmware_nl.po
> +msgstr "Geen filament geladen. Afdrukken geannuleerd."
Although 'afdrukken' is the correct translation for 'to print', in the context of 3D printing it is a bit strange. I suggest to keep the English verb "to print" as that is more commonly used in the community.

So the translation should then be "Geen filament geladen. Printen geannuleerd."

With that said, other translations in this file should be adjusted accordingly for consistency's sake.

2024-08-26 18:36 UTC, gudnimg approved these changes
Looks good to me. :) I’ll wait a bit for translators to review before merging.

2024-08-26 20:58 UTC, AttilaSVK commented
Hungarian should be: "Nincs befűzve filament. Folytassam?" and "Nincs befűzve filament. Nyomtatás megállítva."

2024-08-28 09:00 UTC, DRracer commented on lang/po/Firmware_cs.po
> +msgstr "Není vloženo žádné vlákno. Pokračovat?"
Není vložen filament. Pokračovat?

2024-08-28 09:00 UTC, DRracer commented on lang/po/Firmware_cs.po
> +msgstr "Není vloženo žádné vlákno. Tisk zrušen."
Není vložen filament. Tisk zrušen.

2024-08-28 09:12 UTC, wavexx commented on lang/po/Firmware_it.po
> +
Looking good! You could marginally shorten the message with `Nessun filamento caricato.` as the first sentence if that's beneficial.

2024-08-28 09:42 UTC, 3d-gussner commented
Hi
:croatia: @Prime1910 @PRPA041
:slovakia: @ingbrzy @shatter136
:sweden: @Painkiller56
:norway: @OS-kar @trondkla

Can you please let me know if you will be able to review the changes until end of this week? Also please let me know if you are still interested in reviewing the community translations. If not, I will not ask you anymore and will NOT translate new messages anymore or use "faulty" computer based translations instead.

2024-08-28 09:50 UTC, shatter136 reviewed
Hi. Sorry. In _sk, I would rather write "Nie je vložený filament. ... "
And please keep us still in the loop. Thank you.

2024-08-28 09:56 UTC, ingbrzy requested changes

2024-08-28 09:56 UTC, ingbrzy commented on lang/po/Firmware_sk.po
> +msgstr "Nie je vložené žiadne vlákno. Pokračovať?"
"Nie je zavedený žiaden filament. Pokračovať?"

2024-08-28 09:56 UTC, ingbrzy commented on lang/po/Firmware_sk.po
> +msgstr "Nie je vložené žiadne vlákno. Tlač zrušená."
"Nie je zavedený žiaden filament. Tlač zrušená."

2024-08-28 09:56 UTC, ingbrzy commented on lang/po/Firmware_sk.po
> +msgstr "Nie je vložené žiadne vlákno. Pokračovať?"
@3d-gussner can you update it?
Thank you

2024-08-30 08:35 UTC, merged